north-road/qgis-redistricting-plugin

- redistrict/gui/district_settings_dialog.py
- redistrict/linz/data/mock_electoral_api/status.json
- redistrict/linz/nz_electoral_api.py
- redistrict/test/test_nz_electoral_api.py
Allows testing the auth configuration
> Add API connection test in settings

- redistrict/linz/scenario_base_task.py
- redistrict/linz/validation_task.py
- redistrict/test/test_linz_export_task.py
- redistrict/test/test_linz_scenario_registry.py
- redistrict/test/test_linz_validation_task.py
> Respect offshore meshblocks during validation

- redistrict/redistrict.py
> Allow interactive redistrict tool to be "deselected"

- pylintrc
- redistrict/gui/interactive_redistrict_tool.py
- redistrict/redistrict.py
> Block 'stop redistricting' if unsaved changes in meshblock layer

- redistrict/redistrict.py
> Prevent importing open database as master database

- redistrict/redistrict.py
> Switch to meshblock layer on startup, and when "toggle editing" is clicked

- redistrict/gui/audio_utils.py
- redistrict/gui/district_settings_dialog.py
- redistrict/gui/interactive_redistrict_tool.py
- redistrict/gui/playsound.py
- redistrict/redistrict.py
> Add audio feedback for interactive redistricting

- redistrict/linz/nz_electoral_api.py
> Exclude meshblocks from API results

- redistrict/linz/linz_redistrict_handler.py
> Avoid redistricting a meshblock to the same electorate

- redistrict/linz/nz_electoral_api.py
- redistrict/redistrict.py
- redistrict/test/test_nz_electoral_api.py
> Use correct electorate codes for Stats NZ API compatibility

- redistrict/linz/electorate_changes_queue.py
- redistrict/test/test_linz_electorate_changes_queue.py
> Fix corruption after rollback and redo

- redistrict/linz/linz_district_registry.py
- redistrict/redistrict.py
- redistrict/test/test_create_electorate_dialog.py
- redistrict/test/test_deprecate_electorate_dialog.py
- redistrict/test/test_linz_district_registry.py
- redistrict/test/test_linz_redistrict_gui_handler.py
> Ensure deprecation and scenario are set when creating new electorates

- redistrict/redistrict.py
> Add Rebuild Electorates action

- redistrict/linz/linz_district_registry.py
- redistrict/test/test_create_electorate_dialog.py
- redistrict/test/test_deprecate_electorate_dialog.py
- redistrict/test/test_linz_district_registry.py
- redistrict/test/test_linz_export_task.py
- redistrict/test/test_linz_redistrict_gui_handler.py
- redistrict/test/test_linz_validation_task.py
> Add new field for stats electorate id

- redistrict/core/redistrict_handler.py
- redistrict/linz/linz_redistrict_handler.py
> Update stats dock on undo/redo actions

- redistrict/redistrict.py
Avaliable from the dock settings menu, but requires manual validation
at this stage!
Fixes #116
> Unverified load new meshblock functionality

- redistrict/linz/scenario_selection_dialog.py
- redistrict/redistrict.py
> Switch to last used scenario on plugin load

- redistrict/linz/api_request_queue.py
> Fix exception when cancelling a stats request

- redistrict/redistrict.py
Hopefully never happens outside of my testing!
> Raise warning when the last used scenario no longer exists

- redistrict/linz/api_request_queue.py
> Fix more issues after canceling a stats request

- redistrict/linz/linz_district_registry.py
> Fix warning when creating new electorate

- redistrict/redistrict.py
- redistrict/test/test_interactive_redistrict.py
- redistrict/test/test_linz_mb_scenario_bridge.py
- redistrict/test/test_linz_redistrict_handler.py
- redistrict/test/test_linz_scenario_registry.py
- redistrict/test/utilities.py
Fixes exception when updating meshblock patterns
> Be tolerant when resetting project

- redistrict/linz/linz_validation_results_dock_widget.py
> Don't allow zooming to validation results for entries with no meshblocks assigned

- .github/workflows/build.yml
- .github/workflows/build_artifact_comment.yml
- requirements/packaging.txt
- setup.cfg
This is not yet working in the fork, maybe it will in the main repository.
> Create build comment workflow for pull requests
